name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform plan
        run: terraform plan -out=tfplan

      - name: Approval step
        id: approval
        uses: ChrisCarini/approval-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Please review and approve the Terraform plan"
          reviewers: "weeyin83" # Replace with the GitHub username(s) of the reviewer(s)

      - name: Deploy Terraform infrastructure
        if: steps.approval.outputs.approved == 'true'
        run: terraform apply tfplan
